[package]
name = "chrustical_music"
version = "0.1.0"
authors = ["Huy <huy@hhoang.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.12.1"
hound = "3.4.0"
